version: '3.2'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 38i85Ok32QV&iCXXm
      POSTGRES_DB: octo
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command:
      - ./run.sh
    environment:
      PAGER: 'less -R'

volumes:
    postgres: